services:
  muse:
    image: muse
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./cookies.txt:/cookies.txt
    env_file:
      - .env
    environment:
      DATA_DIR: /data
      DATABASE_URL: "file:/data/prisma.db"
      YT_DLP_COOKIES_PATH: "/cookies.txt"

