services:
  muse:
    image: ghcr.io/nanashithenameless/muse:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./cookies.txt:/cookies.txt
    env_file:
      - .env
    environment:
      DATA_DIR: /data
      DATABASE_URL: "file:/data/prisma.db"
      YT_DLP_COOKIES_PATH: "/cookies.txt"
      YT_DLP_AUTO_UPDATE: "true"
