import {promises as fs} from 'fs';

const YT_DLP_HEADER = '# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.';

export const checkCookieFile = async (cookiePath: string): Promise<void> => {
  let content: string;

  try {
    content = await fs.readFile(cookiePath, 'utf8');
  } catch {
    console.warn(`[cookies] Warning: could not read cookie file at "${cookiePath}"`);
    return;
  }

  // Never modify yt-dlp-generated files
  if (content.startsWith(YT_DLP_HEADER)) {
    return;
  }

  // Normalize: replace tabs with spaces in user-provided files
  const normalized = content.replace(/\t/g, ' ');
  if (normalized !== content) {
    await fs.writeFile(cookiePath, normalized, 'utf8');
    console.log(`[cookies] Replaced tabs with spaces in "${cookiePath}"`);
  }
};
